### ISSUE TITLE
[BUG] phoenix fails to launch when asyncio is nested

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1353]
**Describe the bug**
Follow the llama_index tutorials for agents. It makes asyncio nested and conflicts with uvicorn, failing to launch a thread.

**Comment by RogerHYang** [comment]
Still not able to reproduce this. Is there a specific notebook for which this is occurring?

**Comment by mikeldking** [comment]
Seems to be okay in colab - in vs-code:
```
raceback (most recent call last):
  File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/nest_asyncio.py", line 41, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-8 (run)'.
[/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/threading.py:1011](https://file+.vscode-resource.vscode-cdn.net/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/threading.py:1011): RuntimeWarning: coroutine 'Server.serve' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
💥 Phoenix failed to start. Please try again (making sure that port None is not occupied by another process) or file an issue with us at https://github.com/Arize-ai/phoenix
``

**Comment by mikeldking** [comment]
Confirmed this also works in jupyter - so it seems like it's just a VS code thing. For that reason maybe it's lower priority. However it's pretty jarring so I'd like to bottom this out.

**Comment by RogerHYang** [comment]
was able to reproduce this, but unsure how to fix. looks complicated

**Comment by mikeldking** [comment]
Just hit this in jupyter as well

Existing running Phoenix instance detected! Shutting it down and starting a new instance...
Traceback (most recent call last):
  File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/nest_asyncio.py", line 41, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/nest_asyncio.py", line 68, in get_event_loop
    _patch_loop(loop)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/nest_asyncio.py", line 184, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/threading.py:1011: RuntimeWarning: coroutine 'Server.serve' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
💥 Phoenix failed to start. Please try again (making sure that port 6060 is not occupied by another process) or file an issue with us at https://github.com/Arize-ai/phoenix

**Comment by mikeldking** [comment]
I think the best approach for this is to detect whether or not asyncio is patched and fall back to a process. There is a flag that we can use to detect this. This will be important for us going forward as we must support multiple runtimes.

**Comment by RogerHYang** [comment]
There appears to be a couple of solutions [here](https://github.com/NVIDIA/NeMo-Guardrails/issues/112#issuecomment-1710597461). Want to try those first?

**Comment by RogerHYang** [comment]
We can try adding `loop=` [asyncio](https://github.com/encode/uvicorn/blob/dc205afdbed6707403b267e77fd58aff12d2f9b8/uvicorn/config.py#L37C61-L37C61) to our [Config](https://github.com/Arize-ai/phoenix/blob/34a32c3e8567672bd1ac0979923566c39adecfcf/src/phoenix/server/thread_server.py#L19)

**Comment by RogerHYang** [comment]
adding `loop="asyncio"` fixed the issue

<img width="421" alt="Screenshot 2023-11-18 at 1 38 29 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/b3592d19-90f2-4c17-b627-35a61c501587">

# Before and after
<img width="798" alt="Screenshot 2023-11-18 at 1 38 18 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/62822506-b1b4-451f-a66d-76764db55afe">
