### ISSUE TITLE
[BUG] Can't launch application with imported LangChain traces

### ISSUE THREAD

**Issue by didmar** [Arize-ai/phoenix#1758]
**Describe the bug**
When trying to launch the application with an imported `TraceDataset` from a LangChain workflow, it crashes with the error below.
```python
>>> px.launch_app(trace=ds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/project/venv/lib/python3.10/site-packages/phoenix/session/session.py", line 353, in launch_app
    _session = ThreadSession(
  File "/home/user/project/venv/lib/python3.10/site-packages/phoenix/session/session.py", line 251, in __init__
    super().__init__(
  File "/home/user/project/venv/lib/python3.10/site-packages/phoenix/session/session.py", line 106, in __init__
    self.traces.put(span)
  File "/home/user/project/venv/lib/python3.10/site-packages/phoenix/core/traces.py", line 139, in put
    self._queue.put(encode(span) if isinstance(span, Span) else span)
  File "/home/user/project/venv/lib/python3.10/site-packages/phoenix/trace/v1/__init__.py", line 77, in encode
    attributes=_maybe_struct(_attributes),
  File "/home/user/project/venv/lib/python3.10/site-packages/phoenix/trace/v1/__init__.py", line 528, in _maybe_struct
    return _as_struct(obj) if obj else None
  File "/home/user/project/venv/lib/python3.10/site-packages/phoenix/trace/v1/__init__.py", line 523, in _as_struct
    struct.update(obj)
  File "/home/user/project/venv/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 820, in update
    _SetStructValue(self.fields[key], value)
  File "/home/user/project/venv/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 751, in _SetStructValue
    raise ValueError('Unexpected type')
ValueError: Unexpected type
```

**To Reproduce**
1. Launch Run the following script to create and save to disk a trace:
```python
# pip install langchain arize-phoenix==1.1.1 openai==0.27.4 langchain==0.0.316 
import logging

import phoenix as px
from langchain.chains import LLMChain
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from phoenix.trace.langchain import OpenInferenceTracer, LangChainInstrumentor

px.launch_app()

tracer = OpenInferenceTracer()
LangChainInstrumentor(
    tracer
).instrument()

llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)
prompt = PromptTemplate(input_variables=["input"], template="{input}")
chain = LLMChain(llm=llm, prompt=prompt)

query = "What is your name?"
response = chain(query)
ds = px.TraceDataset.from_spans(tracer.get_spans())
print("Dataset name:", ds.name)
ds.to_disc()
```
2. Run this script to import the traces:
```
import phoenix as px

name = "<replace-with-dataset-name>"

ds = px.TraceDataset.from_name(name)

px.launch_app(trace=ds)
```
3. See error

**Expected behavior**
Application launches and shows the imported traces.

**Environment (please complete the following information):**
 - OS: Linux
 - Python 3.10.12
 - Version 1.1.1

**Comment by mikeldking** [comment]
Thanks for the report @didmar ! Will take a look. Thanks for checking out the project!

**Comment by RogerHYang** [comment]
found the reason: somehow we got an `ndarray` when the data is read back from parquet, even though the original data was just a list

<img width="527" alt="Screenshot 2023-11-21 at 3 41 49 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/7ef1dea2-8abb-4f4d-b9ce-a391e7f4ef0a">

**Comment by RogerHYang** [comment]
i tried [fastparquet](https://stackoverflow.com/a/70771328) and it worked when it's used for both read and write.

<img width="1272" alt="Screenshot 2023-11-21 at 3 54 13 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/dc1db3dd-ca23-4213-95e9-a97a82ca2735">
