### ISSUE TITLE
[Exception while integrating the OpenInferenceTraceCallbackHandler in llamaindex 0.9.7]

### ISSUE THREAD

**Issue by pavanjava** [Arize-ai/phoenix#1803]
**Describe the bug**
While integrating the phoenix to llamaindex 0.9.7 using OpenInferenceTraceCallbackHandler we are encountering expection on `handler.on_event_start` as a result the traces are not visible.

**To Reproduce**
1. Go to 'https://docs.arize.com/phoenix/integrations/llamaindex'
2. follow the code instructions
3. See error below
`Traceback (most recent call last):
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/LLMs/llama_index_tutorials/document_QandA/src/core.py", line 70, in <module>
    result = query_engine.chat("What are the domains the Generative AI used in ?")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/venv-metal/lib/python3.11/site-packages/llama_index/callbacks/utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/venv-metal/lib/python3.11/site-packages/llama_index/agent/react/base.py", line 359, in chat
    reasoning_steps, is_done = self._process_actions(
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/venv-metal/lib/python3.11/site-packages/llama_index/agent/react/base.py", line 190, in _process_actions
    with self.callback_manager.event(
  File "/Users/pavanmantha/miniconda3/envs/tensorflow-research/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/pavanmantha/venv-metal/lib/python3.11/site-packages/llama_index/callbacks/base.py", line 154, in event
    event.on_start(payload=payload)
  File "/Users/pavanmantha/venv-metal/lib/python3.11/site-packages/llama_index/callbacks/base.py", line 247, in on_start
    self._callback_manager.on_event_start(
  File "/Users/pavanmantha/venv-metal/lib/python3.11/site-packages/llama_index/callbacks/base.py", line 89, in on_event_start
    handler.on_event_start(
  File "/Users/pavanmantha/venv-metal/lib/python3.11/site-packages/phoenix/utilities/error_handling.py", line 38, in wrapper
    f"-Args: {args}\n"
              ^^^^`

**Expected behavior**
No Error should occur and it used to work before I upgraded phoenix and llamaindex

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS 14.1.1 (23B81)
 - Notebook Runtime: Python 3.11.4

**Additional context**
I made a debug and found 
` if EventPayload.TOOL in payload:
        tool_metadata = cast(ToolMetadata, payload.get(EventPayload.TOOL))
        attributes[TOOL_NAME] = tool_metadata.name
        attributes[TOOL_DESCRIPTION] = tool_metadata.description
        attributes[TOOL_PARAMETERS] = tool_metadata.to_openai_function()["parameters"]` 
is the code that is causing the issue. the fix will be 
`tool_metadata.to_openai_function()` is returnning a dict with function attribute and in that we have again a dict with `parameters` key as below

`tool_metadata.to_openai_function()['function']['parameters']`

**Comment by axiomofjoy** [comment]
Sounds like this issue has been resolved. @pavanjava I am going to close the issue, but please feel free to re-open if you find that the issue persists.

**Comment by pavanjava** [comment]
Sorry for the late response, yes this issue is fixed after i updated arize-phoenix to latest version
