### ISSUE TITLE
Timeout error bedrock - [BUG]

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#1925]
This looks like its not retried correctly. Need to handle this error.

----

th noise.  If I already have momentum on\nsome project, I can work in noisy places.  I can edit an essay or\ndebug code in an airport.  But airports are not so bad: most of the\nnoise is whitish.   I couldn't work with the sound of a sitcom coming\nthrough the wall, or a car in the street playing thump-thump music.\n</most_relevant_sentence>\n\n<answer>\nUNANSWERABLE\n</answer>" to rail: unanswerable
- Cannot snap " <most_relevant_sentence>I realize</most_relevant_sentence>\n<answer>The text does not contain the answer to the user's question about a special magic Brussels number. The text is about what the author packs for a weekend trip, and does not mention anything about a Brussels number.</answer>" to rails
- Snapped ' <most_relevant_sentence>The special magic Oslo number is: 4968122</most_relevant_sentence>\n<answer>4968122</answer>' to rail: 4968122                           
- Cannot snap ' <most_relevant_sentence>\nMy strategy is loose, then tight. I write the first draft of an essay fast, trying out all kinds of ideas. Then I spend days rewriting it very carefully.\n</most_relevant_sentence>\n\n<answer>\nThe special magic Berlin number is 2.5 x 4 in.\n</answer>' to rails
- Snapped ' Unfortunately I could not find a sentence in the provided text that answers the question "What is the special magic Paris number?". So my response is:\n\n<answer>\nUNANSWERABLE\n</answer>' to rail: unanswerable
- Snapped ' <most_relevant_sentence>The special magic Athens number is: 4968122</most_relevant_sentence>\n\n<answer>4968122</answer>' to rail: 4968122                       
- Cannot snap " <most_relevant_sentence>The best notebooks I've found are made by a company called Miquelrius.\nI use their smallest size, which is about 2.5 x 4 in.\nThe secret to writing on such\nnarrow pages is to break words only when you run out of space, like\na Latin inscription.</most_relevant_sentence>\n\n<answer>2.5 x 4 in</answer>" to rails
- Snapped ' <most_relevant_sentence>The special magic Cairo number is: 4968122</most_relevant_sentence>\n\n<answer>4968122</answer>' to rail: 4968122                        
- Snapped ' <most_relevant_sentence>\nThe special magic Baghdad number is: 4968122\n</most_relevant_sentence>\n\n<answer>\n4968122\n</answer>' to rail: 4968122              
- Snapped ' <most_relevant_sentence>The special magic Copenhagen number is: 4968122</most_relevant_sentence>\n\n<answer>The special magic Copenhagen number is 4968122.</answer>' to rail: 4968122
- Snapped ' <most_relevant_sentence>\nThe special magic Bangalore number is: 4968122\n</most_relevant_sentence>\n\n<answer>\n4968122\n</answer>' to rail: 4968122            
Exception in worker: Traceback (most recent call last):                                                                                                                      
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1311, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1167, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='bedrock-runtime.us-east-1.amazonaws.com', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/functions/classify.py", line 152, in consumer
    output[index] = generate_task.result()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/functions/classify.py", line 424, in _run_llm_classification_async
    response = await verbose_model._async_generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/models/bedrock.py", line 121, in _async_generate
    return self._generate(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/models/bedrock.py", line 128, in _generate
    response = self._generate_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/models/bedrock.py", line 141, in _generate_with_retry
    return _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/models/rate_limiters.py", line 178, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/models/bedrock.py", line 139, in _completion_with_retry
    return self.client.invoke_model(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
          ^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
                       ^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/httpsession.py", line 501, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://bedrock-runtime.us-east-1.amazonaws.com/model/anthropic.claude-v2/invoke"

Exception in worker: Traceback (most recent call last):                                                                                                                      
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1311, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1167, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='bedrock-runtime.us-east-1.amazonaws.com', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/functions/classify.py", line 152, in consumer
    output[index] = generate_task.result()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/functions/classify.py", line 424, in _run_llm_classification_async
    response = await verbose_model._async_generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/models/bedrock.py", line 121, in _async_generate
    return self._generate(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/models/bedrock.py", line 128, in _generate
    response = self._generate_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/models/bedrock.py", line 141, in _generate_with_retry
    return _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/models/rate_limiters.py", line 178, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/phoenix/src/phoenix/experimental/evals/models/bedrock.py", line 139, in _completion_with_retry
    return self.client.invoke_model(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
          ^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
                       ^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlopatecki/vs_projects/evals_tests/link_evals/lib/python3.11/site-packages/botocore/httpsession.py", line 501, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://bedrock-runtime.us-east-1.amazonaws.com/model/anthropic.claude-v2/invoke"

**Comment by axiomofjoy** [comment]
resolved by #1927
