### ISSUE TITLE
[BUG] Runtime Exception when trying to run on fixure llama_index_calculator_agent

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2012]
```
'token_count'

GraphQL request:14:3
13 |   ...SpanColumnSelector_evaluations
14 |   spans(first: 100, sort: {col: startTime, dir: desc}) {
   |   ^
15 |     edges {
Traceback (most recent call last):
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/graphql/execution/execute.py", line 521, in execute_field
    result = resolve_fn(source, info, **args)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 692, in _resolver
    return _get_result_with_extensions(
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 678, in extension_resolver
    return reduce(
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 673, in wrapped_get_result
    return _get_result(
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 634, in _get_result
    return field.get_result(
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/field.py", line 210, in get_result
    return self.base_resolver(*args, **kwargs)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/types/fields/resolver.py", line 203, in __call__
    return self.wrapped_func(*args, **kwargs)
  File "/Users/mikeldking/work/phoenix/src/phoenix/server/api/schema.py", line 272, in spans
    data = list(map(to_gql_span, spans))
  File "/Users/mikeldking/work/phoenix/src/phoenix/server/api/types/Span.py", line 243, in to_gql_span
    _nested_attributes(_hide_embedding_vectors(span.attributes)),
  File "/Users/mikeldking/work/phoenix/src/phoenix/server/api/types/Span.py", line 314, in _nested_attributes
    trie = trie[key]
KeyError: 'token_count'
Stack (most recent call last):
  File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/mikeldking/work/phoenix/src/phoenix/server/main.py", line 191, in <module>
    server.run()
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/asgi/__init__.py", line 111, in __call__
    return await self.handle_http(scope, receive, send)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/asgi/__init__.py", line 178, in handle_http
    response = await self.run(request)
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/http/async_base_view.py", line 176, in run
    result = await self.execute_operation(
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/http/async_base_view.py", line 115, in execute_operation
    return await self.schema.execute(
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/schema/schema.py", line 256, in execute
    result = await execute(
  File "/Users/mikeldking/.virtualenvs/phoenix/lib/python3.10/site-packages/strawberry/schema/execute.py", line 156, in execute
    process_errors(result.errors, execution_context)
    ```

**Comment by mikeldking** [comment]
@RogerHYang if you have time can you root cause this?

**Comment by mikeldking** [comment]
After some investigation it was understood that there is a key error accessing `token_count` on `llm` because `llm` becomes not a default dict in the nesting of attributes at the graphql layer. Seems upstream that `llm` is unfurled to a dict wile also maintaining `llm.token_count.prompt` etc. which causes a conflict and a key error

**Comment by RogerHYang** [comment]
the root cause of this issue is that `llm.messages` is not a semantic convention, so during ingestion it gets broken up into `"llm": {"messages": ...}`. but that creates an occupation on the "llm" key. At render time, the frontend needs to break a semantic convention such as `llm.input_messages` into `"llm": {"input_messages": ...}`, but because the "llm" key is already occupied, it's trying to put the "input_message" key into that existing dict. This is problematic because it would clobber the data. But it's error out because it's trying to access the key in that existing dict and not finding it.

**Comment by RogerHYang** [comment]
This is a temporary issue because we don't break apart semantic conventions during ingestion for backward compatibility reasons. For example, filtering on `llm.input_messages` would try to find the key `"llm.input_message"` on the span instead of doing it as a two step process: first finding the "llm" key and then the "input_messages" key. The latter two-step process would be required if semantic conventions are broken up according to the same rules that we use to break up anything with a `.` (dot). So this issue boils down to the transitory situation where we are making special treatments for the `.` dot notation when the expression is a semantic convention (see [code](https://github.com/Arize-ai/phoenix/blob/3a7bfd2158b5c0ea995f4d1ec00a6f7b2c4a21e8/src/phoenix/trace/otel.py#L235) here). Eventually, we would want to remove this special treatment of semantic conventions, so there is no conflict with non-semantic convention attributes that share the same prefix. To do that we would need to plumb through the rest of the system. For example, we would need to update how filtering is done, as mentioned earlier.
