### ISSUE TITLE
[BUG] [llamaindex] llama-index import error

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#2022]
LlamaIndex has released an update in 0.9.22 that has broken our integration.

```
🌍 To view the Phoenix app in your browser, visit http://127.0.0.1:6006/
📺 To view the Phoenix app in a notebook, run `px.active_session().view()`
📖 For more information on how to use Phoenix, check out https://docs.arize.com/phoenix
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llama_index/callbacks/arize_phoenix_callback.py", line 9, in arize_phoenix_callback_handler
    from phoenix.trace.llama_index import OpenInferenceTraceCallbackHandler
  File "/usr/local/lib/python3.11/site-packages/phoenix/trace/llama_index/__init__.py", line 1, in <module>
    from .callback import OpenInferenceTraceCallbackHandler
  File "/usr/local/lib/python3.11/site-packages/phoenix/trace/llama_index/callback.py", line 40, in <module>
    from llama_index.llms.types import ChatMessage, ChatResponse
ModuleNotFoundError: No module named 'llama_index.llms.types'
```

**Comment by axiomofjoy** [comment]
I suggest downgrading to `llama-index==0.9.21` until this issue is resolved.

**Comment by axiomofjoy** [comment]
> I suggest downgrading to `llama-index==0.9.21` until this issue is resolved.

I misspoke, it appears the user is hitting this issue on an outdated version of LlamaIndex that we no longer support.
