### ISSUE TITLE
[BUG] - Vertex Gemini - Handling response errors

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#2050]
I'm getting a lot of examples from Gemini where a prompt, very specifc data in a prompt, will cause a "errored" response from Gemini.

There are examples where a single word like "irrelevant" causes an error, in other examples some word in summary text is causing an error.

In my summary Evals of 70 items, 2 of the 70 are causing such errors. All are related to something in the summary text itself.

This line is causing errors in all those cases:
    candidate = response.candidates[0]

The returned JSON does not have those objects. We should:
1. print the JSON returned to help debug
2. We should return None for this item/row in the Eval run but we should continue to the Eval run. Erroring out the entire run because of a bad Gemini response kills the entire Eval run. 

Requeuing...
Exception in worker: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/phoenix/experimental/evals/functions/executor.py", line 127, in consumer
    output[index] = generate_task.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.10/dist-packages/phoenix/experimental/evals/functions/classify.py", line 171, in _run_llm_classification_async
    response = await verbose_model._async_generate(
  File "/usr/local/lib/python3.10/dist-packages/phoenix/experimental/evals/models/vertex.py", line 135, in _async_generate
    response = await self._async_generate_with_retry(
  File "/usr/local/lib/python3.10/dist-packages/phoenix/experimental/evals/models/vertex.py", line 155, in _async_generate_with_retry
    return await _completion_with_retry(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/phoenix/experimental/evals/models/vertex.py", line 152, in _completion_with_retry
    candidate = response.candidates[0]
IndexError: list index out of range

**Comment by jlopatec** [comment]
I think the lack of a response on these ones are content protection responses. The examples are here on an internal link:
https://colab.research.google.com/drive/1_0S3m1J9IvKP8ky3nFtBEFlSMDcYRxGT?usp=sharing

We need to handle content protection responses from Gemini in a "clean" fashion as they happen a lot.

**Comment by anticorrelator** [comment]
resolved by #2055
