### ISSUE TITLE
[ENHANCEMENT] Support application/json for OTLP

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2067]
**Is your feature request related to a problem? Please describe.**
By default some exporters just use JSON instead of protos. Right now we reject these mime types but for ease of use we should allow them. 

Example:
```
{"stack":"OTLPExporterError: Unsupported Media Type\n    at IncomingMessage.<anonymous> (/Users/mikeldking/work/arize/arizeweb/node_modules/.pnpm/@opentelemetry+otlp-exporter-base@0.35.0_@opentelemetry+api@1.4.0/node_modules/@opentelemetry/otlp-exporter-base/src/platform/node/util.ts:89:25)\n    at /Users/mikeldking/work/arize/arizeweb/node_modules/.pnpm/@opentelemetry+context-async-hooks@1.9.0_@opentelemetry+api@1.4.0/node_modules/@opentelemetry/context-async-hooks/src/AbstractAsyncHooksContextManager.ts:75:49\n    at AsyncLocalStorage.run (node:async_hooks:335:14)\n    at AsyncLocalStorageContextManager.with (/Users/mikeldking/work/arize/arizeweb/node_modules/.pnpm/@opentelemetry+context-async-hooks@1.9.0_@opentelemetry+api@1.4.0/node_modules/@opentelemetry/context-async-hooks/src/AsyncLocalStorageContextManager.ts:40:36)\n    at IncomingMessage.contextWrapper (/Users/mikeldking/work/arize/arizeweb/node_modules/.pnpm/@opentelemetry+context-async-hooks@1.9.0_@opentelemetry+api@1.4.0/node_modules/@opentelemetry/context-async-hooks/src/AbstractAsyncHooksContextManager.ts:75:26)\n    at IncomingMessage.emit (node:events:526:35)\n    at IncomingMessage.emit (node:domain:488:12)\n    at endReadableNT (node:internal/streams/readable:1589:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","message":"Unsupported Media Type","name":"OTLPExporterError","data":"Unsupported content type: application/json","code":"415"}
``

**Comment by pbadhe** [comment]
Hi @mikeldking, can I know some tests related to this and a bit more description of the issue?
