### ISSUE TITLE
[BUG] cannot build docker image on main branch

### ISSUE THREAD

**Issue by chantlong** [Arize-ai/phoenix#2403]
**Describe the bug**
Dockerfile cannot be build into image.

**To Reproduce**
Cloned the repo and opened the Docker File and ran `docker build -t phoenix .`

**Expected behavior**
Expect Image to be build

**Screenshots**
Error Log

```
0.796 Processing /phoenix
0.798   Installing build dependencies: started
1.528   Installing build dependencies: finished with status 'done'
1.529   Getting requirements to build wheel: started
1.563   Getting requirements to build wheel: finished with status 'done'
1.563   Preparing metadata (pyproject.toml): started
1.629   Preparing metadata (pyproject.toml): finished with status 'error'
1.631   error: subprocess-exited-with-error
1.631
1.631   × Preparing metadata (pyproject.toml) did not run successfully.
1.631   │ exit code: 1
1.631   ╰─> [16 lines of output]
1.631       Traceback (most recent call last):
1.631         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
1.631           main()
1.631         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
1.631           json_out['return_val'] = hook(**hook_input['kwargs'])
1.631         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
1.631           whl_basename = backend.build_wheel(metadata_directory, config_settings)
1.631         File "/tmp/pip-build-env-r4o47ulq/overlay/lib/python3.10/site-packages/hatchling/build.py", line 58, in build_wheel
1.631           return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
1.631         File "/tmp/pip-build-env-r4o47ulq/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 155, in build
1.631           artifact = version_api[version](directory, **build_data)
1.631         File "/tmp/pip-build-env-r4o47ulq/overlay/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 412, in build_standard
1.631           record = archive.add_file(included_file)
1.631         File "/tmp/pip-build-env-r4o47ulq/overlay/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 95, in add_file
1.631           file_stat = os.stat(included_file.path)
1.631       FileNotFoundError: [Errno 2] No such file or directory: '/phoenix/src/phoenix/evals'
1.631       [end of output]
1.631
1.631   note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - Notebook Runtime [e.g. Jupyter, Colab]
 - Version [e.g. 0.0.1]

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)

**Comment by RogerHYang** [comment]
Thanks for filing the issue. It should be fixed now.

**Comment by chantlong** [comment]
Thank you can confirm it works!
