### ISSUE TITLE
[BUG] unknown project graphql error

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#2684]
**Describe the bug**

Upon starting Phoenix, I see the following error in the logs.

```
Unknown project: UHJvamVjdDoz

GraphQL request:4:3
3 | ) {
4 |   node(id: $id) {
  |   ^
5 |     __typename
Traceback (most recent call last):
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/graphql/execution/execute.py", line 521, in execute_field
    result = resolve_fn(source, info, **args)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 692, in _resolver
    return _get_result_with_extensions(
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 678, in extension_resolver
    return reduce(
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 673, in wrapped_get_result
    return _get_result(
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 634, in _get_result
    return field.get_result(
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/field.py", line 210, in get_result
    return self.base_resolver(*args, **kwargs)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/types/fields/resolver.py", line 203, in __call__
    return self.wrapped_func(*args, **kwargs)
  File "/Users/xandersong/phoenix/src/phoenix/server/api/schema.py", line 96, in node
    raise Exception(f"Unknown project: {id}")
Exception: Unknown project: UHJvamVjdDoz
Stack (most recent call last):
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/xandersong/phoenix/src/phoenix/server/main.py", line 254, in <module>
    server.run()
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/asgi/__init__.py", line 111, in __call__
    return await self.handle_http(scope, receive, send)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/asgi/__init__.py", line 178, in handle_http
    response = await self.run(request)
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/http/async_base_view.py", line 176, in run
    result = await self.execute_operation(
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/http/async_base_view.py", line 115, in execute_operation
    return await self.schema.execute(
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/schema/schema.py", line 256, in execute
    result = await execute(
  File "/Users/xandersong/miniforge3/envs/phoenix/lib/python3.8/site-packages/strawberry/schema/execute.py", line 156, in execute
    process_errors(result.errors, execution_context)
```

**To Reproduce**
Run Phoenix from the command line on latest main.

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: latest main

**Comment by axiomofjoy** [comment]
This error appears to disappear after clearing my browser cache.

**Comment by mikeldking** [comment]
It's because you have a tab open and it's refreshing on a node that no longer exists

**Comment by axiomofjoy** [comment]
Got it, thanks
