### ISSUE TITLE
async migrations failing in notebook event loop

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2853]

**Comment by RogerHYang** [comment]
Actually, the migration is run before the thread is created, so it's having trouble running the task using the notebook's event loop. I'm getting the following exception:

```
Traceback (most recent call last):
  File "/Users/rogeryang/phoenix/src/phoenix/db/migrations/env.py", line 103, in run_migrations
    context.configure(
  File "<string>", line 8, in configure
AttributeError: 'NoneType' object has no attribute 'configure'
```
