### ISSUE TITLE
[BUG] error pulling events using sqlite

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3008]
```
ERROR [strawberry.execution] 'name'

GraphQL request:88:3

87 |   ...SpanColumnSelector_evaluations

88 |   rootSpans: spans(first: 100, sort: {col: startTime, dir: desc}, rootSpansOnly: true, timeRange: $timeRange) {

|   ^

89 |     edges {

Traceback (most recent call last):

File "/phoenix/env/graphql/execution/execute.py", line 528, in await_result

return_type, field_nodes, info, path, await result

^^^^^^^^^^^^

File "/phoenix/env/strawberry/schema/schema_converter.py", line 704, in _async_resolver

return await await_maybe(

^^^^^^^^^^^^^^^^^^

File "/phoenix/env/strawberry/utils/await_maybe.py", line 12, in await_maybe

return await value

^^^^^^^^^^^

File "/phoenix/env/phoenix/server/api/types/Project.py", line 201, in spans

data = [to_gql_span(span) for span in spans]

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/phoenix/env/phoenix/server/api/types/Project.py", line 201, in <listcomp>

data = [to_gql_span(span) for span in spans]

^^^^^^^^^^^^^^^^^

File "/phoenix/env/phoenix/server/api/types/Span.py", line 187, in to_gql_span

events: List[SpanEvent] = list(map(SpanEvent.from_dict, span.events))

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/phoenix/env/phoenix/server/api/types/Span.py", line 91, in from_dict

name=event["name"],

~~~~~^^^^^^^^

KeyError: 'name'

Stack (most recent call last):

File "<frozen runpy>", line 198, in _run_module_as_main

File "<frozen runpy>", line 88, in _run_code

File "/phoenix/env/phoenix/server/main.py", line 247, in <module>

server.run()

File "/phoenix/env/uvicorn/server.py", line 65, in run

return asyncio.run(self.serve(sockets=sockets))

File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run

return runner.run(main)

File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run

return self._loop.run_until_complete(task)

File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete

self.run_forever()

File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever

self._run_once()

File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once

handle._run()

File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run

self._context.run(self._callback, *self._args)

File "/phoenix/env/starlette/middleware/base.py", line 151, in coro

await self.app(scope, receive_or_disconnect, send_no_error)

File "/phoenix/env/starlette/middleware/exceptions.py", line 65, in __call__

await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

File "/phoenix/env/starlette/_exception_handler.py", line 53, in wrapped_app

await app(scope, receive, sender)

File "/phoenix/env/starlette/routing.py", line 756, in __call__

await self.middleware_stack(scope, receive, send)

File "/phoenix/env/starlette/routing.py", line 776, in app

await route.handle(scope, receive, send)

File "/phoenix/env/starlette/routing.py", line 297, in handle

await self.app(scope, receive, send)

File "/phoenix/env/strawberry/asgi/__init__.py", line 111, in __call__

return await self.handle_http(scope, receive, send)

File "/phoenix/env/strawberry/asgi/__init__.py", line 178, in handle_http

response = await self.run(request)

File "/phoenix/env/strawberry/http/async_base_view.py", line 176, in run

result = await self.execute_operation(

File "/phoenix/env/strawberry/http/async_base_view.py", line 115, in execute_operation

return await self.schema.execute(

File "/phoenix/env/strawberry/schema/schema.py", line 256, in execute

result = await execute(

File "/phoenix/env/strawberry/schema/execute.py", line 156, in execute

process_errors(result.errors, execution_context)
```

**Comment by mikeldking** [comment]
probably because there are errors
