### ISSUE TITLE
ERROR:openinference.instrumentation.langchain._tracer:Failed to get attribute

### ISSUE THREAD

**Issue by cmosguy** [Arize-ai/phoenix#3120]
I am doing simple langchain and langgraph stuff.
```python
import phoenix as px
from phoenix.trace.langchain import LangChainInstrumentor
px.launch_app()
LangChainInstrumentor().instrument()

run my workflow here
```

When I run the my langgraph workflow, I see:
```python
ERROR:openinference.instrumentation.langchain._tracer:Failed to get attribute.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/proj/lib/python3.10/site-packages/openinference/instrumentation/langchain/_tracer.py", line 236, in wrapper
    yield from wrapped(*args, **kwargs)
  File "/opt/miniconda3/envs/proj/lib/python3.10/site-packages/openinference/instrumentation/langchain/_tracer.py", line 325, in _input_messages
    assert hasattr(message_data, "get"), f"expected Mapping, found {type(message_data)}"
AssertionError: expected Mapping, found <class 'tuple'>
ERROR:openinference.instrumentation.langchain._tracer:Failed to get attribute.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/proj/lib/python3.10/site-packages/openinference/instrumentation/langchain/_tracer.py", line 236, in wrapper
    yield from wrapped(*args, **kwargs)
  File "/opt/miniconda3/envs/proj/lib/python3.10/site-packages/openinference/instrumentation/langchain/_tracer.py", line 325, in _input_messages
    assert hasattr(message_data, "get"), f"expected Mapping, found {type(message_data)}"
AssertionError: expected Mapping, found <class 'tuple'>
```
I am using versions:
```
arize-phoenix==3.23.0
openinference-instrumentation==0.1.1
openinference-instrumentation-langchain==0.1.14
openinference-instrumentation-llama-index==1.2.1
openinference-instrumentation-openai==0.1.4
openinference-semantic-conventions==0.1.5
opentelemetry-api==1.24.0
opentelemetry-exporter-otlp==1.24.0
opentelemetry-exporter-otlp-proto-common==1.24.0
opentelemetry-exporter-otlp-proto-grpc==1.24.0
opentelemetry-exporter-otlp-proto-http==1.24.0
opentelemetry-instrumentation==0.45b0
opentelemetry-instrumentation-asgi==0.45b0
opentelemetry-instrumentation-fastapi==0.45b0
opentelemetry-proto==1.24.0
opentelemetry-sdk==1.24.0
opentelemetry-semantic-conventions==0.45b0
opentelemetry-util-http==0.45b0
langchain==0.1.16
langchain-community==0.0.33
langchain-core==0.1.48
langchain-openai==0.1.4
langchain-text-splitters==0.0.1
langchainhub==0.1.15
openinference-instrumentation-langchain==0.1.14
```

**Comment by axiomofjoy** [comment]
Thanks for reporting @cmosguy. Can you send a snippet of the LangChain code to reproduce?

**Comment by axiomofjoy** [comment]
@cmosguy I am not able to reproduce the issue on the [notebook link](https://github.com/langchain-ai/langgraph/blob/main/examples/multi_agent/agent_supervisor.ipynb) you sent. I am able to get traces from this notebook into Phoenix. Here's a link to a slightly modified version that is working for me. https://colab.research.google.com/drive/1xDEPe2i_2rRqs7o6oNTtqA4J7Orsnvx1?usp=sharing

Here are some relevant requirements.

```
arize-phoenix==4.0.0
langchain==0.1.19
langchain-core==0.1.52
langchain-experimental==0.0.58
langchain-openai==0.1.6
langgraph==0.0.48
openai==1.27.0
openinference-instrumentation==0.1.5
openinference-instrumentation-langchain==0.1.14
openinference-instrumentation-openai==0.1.4
opentelemetry-api==1.24.0
opentelemetry-exporter-otlp==1.24.0
opentelemetry-exporter-otlp-proto-common==1.24.0
opentelemetry-exporter-otlp-proto-grpc==1.24.0
opentelemetry-exporter-otlp-proto-http==1.24.0
opentelemetry-instrumentation==0.45b0
opentelemetry-proto==1.24.0
opentelemetry-sdk==1.24.0
opentelemetry-semantic-conventions==0.45b0
```
