### ISSUE TITLE
[BUG] The password for database has ! will report an error.

### ISSUE THREAD

**Issue by realjustinwu** [Arize-ai/phoenix#3402]
**Describe the bug**
The password for database has ! will report an error.

**To Reproduce**
1. Update docker-compose.yaml
```yaml
# docker-compose.yml
services:
  phoenix:
    image: arizephoenix/phoenix:latest # Must be greater than 4.0 version to work
    depends_on:
      - db
    ports:
      - 6006:6006  # PHOENIX_PORT
      - 4317:4317  # PHOENIX_GRPC_PORT
      - 9090:9090  # [Optional] PROMETHEUS PORT IF ENABLED
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://postgres:postgres!123@db:5432/postgres
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres!123
      - POSTGRES_DB=postgres
    ports:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data:
    driver: local
```
3. Run `docker compose up -d`
4. Run `docker logs phoenix-pro-1` to check the log

```text
➜  phoenix docker logs phoenix-pro-1
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
/phoenix/env/phoenix/server/main.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
🏃‍♀️‍➡️ Running migrations on the database.
---------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/phoenix/env/phoenix/db/migrate.py", line 47, in migrate
    raise e
  File "/phoenix/env/phoenix/db/migrate.py", line 40, in migrate
    alembic_cfg.set_main_option("sqlalchemy.url", str(url))
  File "/phoenix/env/alembic/config.py", line 272, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "/phoenix/env/alembic/config.py", line 299, in set_section_option
    self.file_config.set(section, name, value)
  File "/usr/lib/python3.11/configparser.py", line 1220, in set
    super().set(section, option, value)
  File "/usr/lib/python3.11/configparser.py", line 910, in set
    value = self._interpolation.before_set(self, section, option,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 403, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in 'postgresql+asyncpg://postgres:***@db:5432/postgres?password=postgres%21123&user=postgres' at position 68
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/phoenix/env/phoenix/db/migrate.py", line 47, in migrate
    raise e
  File "/phoenix/env/phoenix/db/migrate.py", line 40, in migrate
    alembic_cfg.set_main_option("sqlalchemy.url", str(url))
  File "/phoenix/env/alembic/config.py", line 272, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "/phoenix/env/alembic/config.py", line 299, in set_section_option
    self.file_config.set(section, name, value)
  File "/usr/lib/python3.11/configparser.py", line 1220, in set
    super().set(section, option, value)
  File "/usr/lib/python3.11/configparser.py", line 910, in set
    value = self._interpolation.before_set(self, section, option,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 403, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in 'postgresql+asyncpg://postgres:***@db:5432/postgres?password=postgres%21123&user=postgres' at position 68

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/phoenix/env/phoenix/server/app.py", line 326, in create_app
    engine = create_engine(database_url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/phoenix/env/phoenix/db/engines.py", line 77, in create_engine
    return aio_postgresql_engine(url=url, migrate=migrate, echo=echo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/phoenix/env/phoenix/db/engines.py", line 132, in aio_postgresql_engine
    migrate_in_thread(engine.url)
  File "/phoenix/env/phoenix/db/migrate.py", line 71, in migrate_in_thread
    raise PhoenixMigrationError(error_message) from result
phoenix.exceptions.PhoenixMigrationError: 

Unable to migrate configured Phoenix DB. Original error:
ValueError: invalid interpolation syntax in 'postgresql+asyncpg://postgres:***@db:5432/postgres?password=postgres%21123&user=postgres' at position 68

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/phoenix/env/phoenix/server/main.py", line 243, in <module>
    app = create_app(
          ^^^^^^^^^^^
  File "/phoenix/env/phoenix/server/app.py", line 340, in create_app
    raise PhoenixMigrationError(msg) from e
phoenix.exceptions.PhoenixMigrationError: 

⚠️⚠️ Phoenix failed to migrate the database to the latest version. ⚠️⚠️

The database may be in a dirty state. To resolve this, the Alembic CLI can be used
from the `src/phoenix/db` directory inside the Phoenix project root. From here,
revert any partial migrations and run `alembic stamp` to reset the migration state,
then try starting Phoenix again.

If issues persist, please reach out for support in the Arize community Slack:
https://arize-ai.slack.com

You can also refer to the Alembic documentation for more information:
https://alembic.sqlalchemy.org/en/latest/tutorial.html
```

**Expected behavior**
The container can be started normally

**Environment (please complete the following information):**
 - OS: MacOS
 - Version: 4.2.4

**Comment by axiomofjoy** [comment]
@realjustinwu Can you trying encoding your password in your URI string?

```
>>> import urllib.parse
>>> urllib.parse.quote_plus("postgres!123")
'postgres%21123'
```

Relevant resources:

- https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
- https://docs.sqlalchemy.org/en/20/core/engines.html#database-urls

**Comment by RogerHYang** [comment]
@realjustinwu Can you try again with our latest release Phoenix v[4.3.0](https://pypi.org/project/arize-phoenix/4.3.0/)?
