### ISSUE TITLE
[BUG] importing phoenix fails when running inside Docker.

### ISSUE THREAD

**Issue by Verizane** [Arize-ai/phoenix#3530]
**Describe the bug**
import of phoenix inside a dockerfile fails. Stacktrace:
```Traceback (most recent call last):
  
File "/usr/src/app/./script.py", line 1, in <module>
    import phoenix as px
  
File "/usr/local/lib/python3.11/site-packages/phoenix/__init__.py", line 12, in <module>
    from .session.session import (
  
File "/usr/local/lib/python3.11/site-packages/phoenix/session/session.py", line 43, in <module>
    from phoenix.server.app import create_app
  
File "/usr/local/lib/python3.11/site-packages/phoenix/server/app.py", line 74, in <module>
    from phoenix.server.api.schema import schema
  
File "/usr/local/lib/python3.11/site-packages/phoenix/server/api/schema.py", line 16, in <module>
    from phoenix.pointcloud.clustering import Hdbscan
  
File "/usr/local/lib/python3.11/site-packages/phoenix/pointcloud/clustering.py", line 6, in <module>
    from hdbscan import HDBSCAN
  
File "/usr/local/lib/python3.11/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  
File "/usr/local/lib/python3.11/site-packages/hdbscan/hdbscan_.py", line 20, in <module>
    from ._hdbscan_linkage import (
  
File "hdbscan/_hdbscan_linkage.pyx", line 1, in init hdbscan._hdbscan_linkage

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**To Reproduce**
1. Dockerfile:
```
FROM python:3.11.9-bookworm AS python-build

WORKDIR /usr/src/app

COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r ./requirements.txt

CMD [ "python", "./script.py" ]
```

requirements.txt:
```
arize-phoenix

structlog

weaviate-client

python-dotenv

llama-index

llama-index-vector-stores-weaviate
```

script.py:
```
import phoenix as px
```

2. inside directory from bash shell call:
```
docker build -t phoenix-test -f ./Dockerfile . && docker run phoenix-test
```

**Expected behavior**
Import inside Docker container should run without problems

**Environment (please complete the following information):**
 - OS: Any Docker instance. Run on both Windows and Debian

**Comment by RogerHYang** [comment]
This is caused by the new numpy 2.0

**Comment by RogerHYang** [comment]
This issue was caused by the release of numpy 2.0, but it looks like it has been fixed upstream. Can you try again?

**Comment by Verizane** [comment]
> This issue was caused by the release of numpy 2.0, but it looks like it has been fixed upstream. Can you try again?

I have built it from scratch and the error is the same. the numpy version is 2.0.0

**Comment by RogerHYang** [comment]
ok. looks like this error is from hdbscan. i think we'll have to restrict the numpy version

**Comment by RogerHYang** [comment]
i filed an [issue](https://github.com/scikit-learn-contrib/hdbscan/issues/642) with hdbscan. I'll add a restriction on phoenix

**Comment by Verizane** [comment]
Thank you, with Version 4.4.3 it is solved!
