### ISSUE TITLE
Cannot run Arize Phoenix separately on a local server

### ISSUE THREAD

**Issue by girijesh97** [Arize-ai/phoenix#3852]
**Describe the bug**
I have flask application in which I am trying to add Arize Phoenix for observability. I have added manual instrumentation for Open AI. What could be done here to run flask and Arize separately. Any help would be greatly appreciated. 

I also checked this bug but it didn't help: https://github.com/Arize-ai/phoenix/issues/3067

**To Reproduce**
1. Copy paste the code
2. Run: flask --app <script_name> run

**Expected behavior**
I am expecting to run Flask server and Arize  separately

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS]
 - Flask server
 - Browser:  chrome
 - Version 

**Additional context**
Code: `from flask import Flask
from openai import AzureOpenAI
import phoenix as px
from azure.identity import DefaultAzureCredential, get_bearer_token_provider, ManagedIdentityCredential
from opentelemetry.sdk.resources import Resource
import os
from phoenix.trace.openai import OpenAIInstrumentor
from openinference.semconv.resource import ResourceAttributes
from opentelemetry import trace as trace_api
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace.export import SimpleSpanProcessor

app = Flask(__name__)

os.environ["PHOENIX_PROJECT_NAME"] = "dummyDemo"
os.environ["PHOENIX_HOST"] = "http://127.0.0.1:6006"
os.environ["PHOENIX_PORT"] = "6006"
os.environ["PHOENIX_COLLECTOR_ENDPOINT"] = "http://127.0.0.1:6006"

phoenix_session = px.launch_app()

resource=Resource(attributes=[])
resource = Resource(attributes={
    ResourceAttributes.PROJECT_NAME: 'dummyDemo'
})
tracer_provider = trace_sdk.TracerProvider(resource=resource)
span_exporter = OTLPSpanExporter(endpoint="http://127.0.0.1:6006")
span_processor = SimpleSpanProcessor(span_exporter=span_exporter)
tracer_provider.add_span_processor(span_processor=span_processor)
trace_api.set_tracer_provider(tracer_provider=tracer_provider)
# Add any auto-instrumentation you want 
OpenAIInstrumentor().instrument()

azure_credential = DefaultAzureCredential()
token_provider = get_bearer_token_provider(azure_credential, "https://cognitiveservices.azure.com/.default")
client = AzureOpenAI(
                    azure_endpoint = f"https:abc.openai.azure.com", 
                    api_version = "2024-02-15-preview",
                    azure_ad_token_provider = token_provider,
                    )

def instrument():
    conversation = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Hello, can you help me with something?"}
    ]
    # Generate a response from the assistant
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=conversation,
    )
    print(response.choices[0].message.content)

@app.route("/")
def hello_world():
    instrument()
    return "<p>Hello, World!</p>"`

Error:

`WARNING:phoenix.session.session:⚠️ PHOENIX_COLLECTOR_ENDPOINT is set to http://127.0.0.1:6006.
⚠️ This means that traces will be sent to the collector endpoint and not this app.
⚠️ If you would like to use this app to view traces, please unset this environmentvariable via e.g. `del os.environ['PHOENIX_COLLECTOR_ENDPOINT']` 
⚠️ You will need to restart your notebook to apply this change.
ERROR:    [Errno 8] nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/server.py", line 162, in startup
    server = await loop.create_server(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1491, in create_server
    infos = await tasks.gather(*fs)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1423, in _create_server_getaddrinfo
    infos = await self._ensure_resolved((host, port), family=family,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1419, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/server.py", line 84, in _serve
    await self.startup(sockets=sockets)
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/server.py", line 172, in startup
    sys.exit(1)
SystemExit: 1
ERROR [phoenix.session.session] 💥 Phoenix failed to start. Please try again (making sure that port 6006 is not occupied by another process) or file an issue with us at https://github.com/Arize-ai/phoenix
 * Serving Flask app 'arize_flask'
 * Debug mode: off
INFO  [werkzeug] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO  [werkzeug] Press CTRL+C to quit`

**Comment by girijesh97** [comment]
Had to flask and arize phoenix separately on two different server

**Comment by axiomofjoy** [comment]
> Had to run flask and arize phoenix separately on two different server

@girijesh97 It looks like you resolved this issue. Closing, but feel free to re-open if the issue persists.
