### ISSUE TITLE
[BUG] In a new conda enviroment, I get an import error for OpenInference span kinds

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3986]
(new) ➜  work (⎈|mynamespace:mikeldking)python -m phoenix.server.main serve
zsh: command not found: python
(new) ➜  work (⎈|mynamespace:mikeldking)python3 -m phoenix.server.main serve
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/mikeldking/work/phoenix/src/phoenix/__init__.py", line 4, in <module>
    from .session.client import Client
  File "/Users/mikeldking/work/phoenix/src/phoenix/session/client.py", line 47, in <module>
    from phoenix.experiments.types import Dataset, Example
  File "/Users/mikeldking/work/phoenix/src/phoenix/experiments/__init__.py", line 1, in <module>
    from .functions import evaluate_experiment, run_experiment
  File "/Users/mikeldking/work/phoenix/src/phoenix/experiments/functions.py", line 776, in <module>
    EVALUATOR = OpenInferenceSpanKindValues.EVALUATOR.value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py", line 783, in __getattr__
    raise AttributeError(name) from None
AttributeError: EVALUATOR

**Comment by RogerHYang** [comment]
I think we forgot the pin the new version on Conda

**Comment by RogerHYang** [comment]
It turns out we did update it on Conda: below shows the correct version when I try to install from scratch.

<img width="418" alt="Screenshot 2024-07-24 at 3 29 04 PM" src="https://github.com/user-attachments/assets/fe010ac8-7645-40db-b064-feae711cacb7">

**Comment by mikeldking** [comment]
Oh sorry this was user error on my part @RogerHYang. For some conda environments, if you do not specify the python version it defaults to your local python environment - this wasn't the behavior I expected.
