### ISSUE TITLE
[BUG] Users expressing that evals subpackage not installed on fresh install

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3988]
```
Traceback (most recent call last):
  File "/app/new_app.py", line 9, in <module>
    import phoenix as px
  File "/app/arize_phoenix-4.14.1/src/phoenix/__init__.py", line 4, in <module>
    from .session.client import Client
  File "/app/arize_phoenix-4.14.1/src/phoenix/session/client.py", line 47, in <module>
    from phoenix.experiments.types import Dataset, Example
  File "/app/arize_phoenix-4.14.1/src/phoenix/experiments/__init__.py", line 1, in <module>
    from .functions import evaluate_experiment, run_experiment
  File "/app/arize_phoenix-4.14.1/src/phoenix/experiments/functions.py", line 45, in <module>
    from phoenix.evals.executors import get_executor_on_sync_context
ModuleNotFoundError: No module named 'phoenix.evals'
```

**Comment by mikeldking** [comment]
Cannot repro - closing
