### ISSUE TITLE
PORT Binding + Encoding Error on Windows Environment

### ISSUE THREAD

**Issue by mjdyibrahim** [Arize-ai/phoenix#4207]
**Describe the bug**
I was not able to get started on Windows, consistently getting the below errors logs:

I tried adding environment variables for encoding and changing the default ports to no avails. 

```
PHOENIX_PORT=4004 
PHOENIX_GRPC_PORT=5701
PYTHONIOENCODING=utf-8
PYTHONLEGACYWINDOWSSTDIO=utf-8
GRPC_VERBOSITY=debug

```
I tried setting the encoding in the code:

```
# # Set the encoding for windows
# if os.name == 'nt':  # Check if the OS is Windows
#     sys.stdout.reconfigure(encoding='utf-8')
#     sys.stderr.reconfigure(encoding='utf-8')
```

--- Logging error ---
```
Traceback (most recent call last):
  File "C:\Users\amagd\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  **File "C:\Users\amagd\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]**
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4cb' in position 0: character maps to <undefined>
Call stack:
  File "C:\Users\amagd\projects\falcon\app.py", line 21, in <module>
    import phoenix as px
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\__init__.py", line 1, in <module>
    from .inferences.fixtures import ExampleInferences, load_example
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\inferences\fixtures.py", line 12, in <module>
    from phoenix.config import INFERENCES_DIR
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\config.py", line 209, in <module>
    ensure_working_dir()
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\config.py", line 190, in ensure_working_dir
    logger.info(f"📋 Ensuring phoenix working directory: {WORKING_DIR}")
Message: '📋 Ensuring phoenix working directory: C:\\Users\\amagd\\.phoenix'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\amagd\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  **File "C:\Users\amagd\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4cb' in position 0: character maps to <undefined>
Call stack:**
  File "C:\Users\amagd\projects\falcon\app.py", line 37, in <module>
    phoenix_session = px.launch_app()
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\session\session.py", line 501, in launch_app
    ensure_working_dir()
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\config.py", line 190, in ensure_working_dir
    logger.info(f"📋 Ensuring phoenix working directory: {WORKING_DIR}")
Message: '📋 Ensuring phoenix working directory: C:\\Users\\amagd\\.phoenix'
Arguments: ()
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1723317029.437847    3856 log.cc:142] Log level DEBUG is not suitable for production. Prefer WARNING or ERROR. However if you see this message in a debug environmenmt or test environmenmt it is safe to ignore this message.
🌍 To view the Phoenix app in your browser, visit http://localhost:4004/
📖 For more information on how to use Phoenix, check out https://docs.arize.com/phoenix
 * Serving Flask app 'app'
 * Debug mode: on
INFO  [werkzeug] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO  [werkzeug] Press CTRL+C to quit
INFO  [werkzeug]  * Restarting with stat
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\amagd\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\amagd\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4cb' in position 0: character maps to <undefined>
Call stack:
  File "C:\Users\amagd\projects\falcon\app.py", line 21, in <module>
    import phoenix as px
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\__init__.py", line 1, in <module>
    from .inferences.fixtures import ExampleInferences, load_example
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\inferences\fixtures.py", line 12, in <module>
    from phoenix.config import INFERENCES_DIR
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\config.py", line 209, in <module>
    ensure_working_dir()
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\config.py", line 190, in ensure_working_dir
    logger.info(f"≡ƒôï Ensuring phoenix working directory: {WORKING_DIR}")
Message: '≡ƒôï Ensuring phoenix working directory: C:\\Users\\amagd\\.phoenix'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\amagd\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  **File "C:\Users\amagd\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4cb' in position 0: character maps to <undefined>
Call stack:**
  File "C:\Users\amagd\projects\falcon\app.py", line 37, in <module>
    phoenix_session = px.launch_app()
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\session\session.py", line 501, in launch_app
    ensure_working_dir()
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\config.py", line 190, in ensure_working_dir
    logger.info(f"≡ƒôï Ensuring phoenix working directory: {WORKING_DIR}")
Message: '≡ƒôï Ensuring phoenix working directory: C:\\Users\\amagd\\.phoenix'
Arguments: ()
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1723317050.292450   22764 log.cc:142] Log level DEBUG is not suitable for production. Prefer WARNING or ERROR. However if you see this message in a debug environmenmt or test environmenmt it is safe to ignore this message.
E0000 00:00:1723317050.316634   22764 chttp2_server.cc:1143] UNKNOWN:No address added out of total 1 resolved for '[::]:5701' {created_time:"2024-08-10T19:10:50.2986144+00:00", children:[UNKNOWN:Failed to prepare server socket {created_time:"2024-08-10T19:10:50.2985249+00:00", fd:2792, children:[UNAVAILABLE:bind: WSA Error (Only one usage of each socket address (protocol/network address/port) is normally permitted.  
 -- 10048) {created_time:"2024-08-10T19:10:50.2984317+00:00", grpc_status:14}]}]}
ERROR:    Traceback (most recent call last):
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\starlette\routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\amagd\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\server\app.py", line 239, in lifespan
    async with bulk_inserter as (
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\phoenix\server\grpc_server.py", line 80, in __aenter__
    server.add_insecure_port(f"[::]:{get_env_grpc_port()}")
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\grpc\aio\_server.py", line 102, in add_insecure_port
    return _common.validate_port_binding_result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amagd\projects\falcon\venv\Lib\site-packages\grpc\_common.py", line 181, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address [::]:5701; set GRPC_VERBOSITY=debug environment variable to see detailed error message.

ERROR:    Application startup failed. Exiting.
ERROR [phoenix.session.session] ≡ƒÆÑ Phoenix failed to start. Please try again (making sure that port 4004 is not occupied by another process) or file an issue with us at https://github.com/Arize-ai/phoenix
WARNI [werkzeug]  * Debugger is active!
INFO  [werkzeug]  * Debugger PIN: 284-988-027
```

**To Reproduce**
1. try running phoenix on windows environment

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Notebook Runtime: Visual Studio Code
 - Version 4.22.0

**Additional context**
I followed the explained process in the documentation 

```
import phoenix 
...
phoenix_session = px.launch_app()
```

**Comment by RogerHYang** [comment]
This for the report, @mjdyibrahim.

For the encoding problem, can you try disabling logging via the following (for the time being)?
```python
import logging

for name, logger in logging.root.manager.loggerDict.items():
    if name.startswith("phoenix.") and isinstance(logger, logging.Logger):
        logger.setLevel(logging.ERROR)
        logger.handlers.clear()
        logger.addHandler(logging.NullHandler())
```

**Comment by mjdyibrahim** [comment]
Thanks Roger, though, the above did not work.

1. To avoid getting the Encoding error on windows, I manually deleted emjois and special characters from corresponding files (e.g. phoenix/session/session.py, phoenix/db/migrate.py, phoenix/server/app.py, .etc)

2. I had to manually delete phoenix.db file to avoid the port binding issue, it seems that when the process exited, the file open state did not close.

3. I also had to change phoenix\server\main.py on line 274

From: 

`ui_path = **PosixPath**(f"http://{host}:{port}", host_root_path)
`
To:

`ui_path = **Path**(f"http://{host}:{port}", host_root_path)
`

Since PosixPath is not supported on Windows.

This might work out of the box for multiplatform:

```
import platform
from pathlib import Path

if platform.system() == "Windows":
    from pathlib import WindowsPath as Path
else:
    from pathlib import PosixPath as Path
```

**Comment by RogerHYang** [comment]
Thank you for your insights!

We'll work on a fix on our end.

**Comment by RogerHYang** [comment]
@mjdyibrahim We were not able to reproduce the following issue, but were otherwise able to fix the application launch for Windows in the latest release (4.25.0). Could you please give that a try and see if this issue still persists?

> 2. I had to manually delete phoenix.db file to avoid the port binding issue, it seems that when the process exited, the file open state did not close.
