### ISSUE TITLE
[BUG] PydanticSerializationError when Running Phoenix with LlamaIndex

### ISSUE THREAD

**Issue by daringcalf** [Arize-ai/phoenix#4423]
**Describe the bug**
When running the provided Python script using the Phoenix and LlamaIndex libraries, an error occurs during the process of serializing output to JSON. Specifically, a `PydanticSerializationError` is raised, indicating that a `'MockValSer'` object cannot be converted to `'SchemaSerializer'`.

**To Reproduce**
```python
import phoenix as px
from openinference.instrumentation.llama_index import LlamaIndexInstrumentor
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.trace.export import SimpleSpanProcessor

from llama_index.llms.openrouter import OpenRouter
from llama_index.llms.neutrino import Neutrino
from llama_index.core import Settings

from dotenv import load_dotenv

load_dotenv()

from llama_index.core import VectorStoreIndex, SimpleDirectoryReader

session = px.launch_app()

endpoint = "http://127.0.0.1:6006/v1/traces"
tracer_provider = trace_sdk.TracerProvider()
tracer_provider.add_span_processor(SimpleSpanProcessor(OTLPSpanExporter(endpoint)))

LlamaIndexInstrumentor().instrument(tracer_provider=tracer_provider)

llm1 = OpenRouter("openai/gpt-4o-mini")
llm2 = Neutrino(
  model="chat-preview",
  api_base="https://router.neutrinoapp.com/api/engines",
)

Settings.llm = llm1 # llm2 will cause error as well

documents = SimpleDirectoryReader("files").load_data() # files dir contains 2 dummy text files
index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()
response = query_engine.query("summarize each document in a few sentences")

input("Press <ENTER> to exit..."
```
Run the script with `python main.py`, observe the error in the console output.
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
INFO:phoenix.config:📋 Ensuring phoenix working directory: /Users/daringcalf/.phoenix
🌍 To view the Phoenix app in your browser, visit http://localhost:6006/
📖 For more information on how to use Phoenix, check out https://docs.arize.com/phoenix
INFO  [phoenix.server.app] Loading trace fixtures...
INFO  [phoenix.server.app] Finished loading fixtures.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1724865355.513207 331510603 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1724865355.551660 331510603 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
ERROR [openinference.instrumentation.llama_index._handler] Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
Traceback (most recent call last):
  File "/Users/daringcalf/.local/share/virtualenvs/phoenix-F7TaqKv7/lib/python3.12/site-packages/openinference/instrumentation/llama_index/_handler.py", line 248, in process_output
    self[OUTPUT_VALUE] = result.model_dump_json(exclude_unset=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daringcalf/.local/share/virtualenvs/phoenix-F7TaqKv7/lib/python3.12/site-packages/pydantic/main.py", line 415, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

**Expected behavior**
The code should execute without raising a `PydanticSerializationError`

**Environment:**
 - OS: macOS 14.4.1 (23E224)
 - python: 3.12.5
 ```
arize-phoenix = "4.31.0"
llama-index = "0.11.2"
openinference-instrumentation-llama-index = "3.0.0"
opentelemetry-proto = "1.26.0"
pydantic = "2.8.2"
pydantic-core = "2.20.1"
llama-index-llms-neutrino = "0.2.0"
llama-index-llms-openrouter = "0.2.0"
llama-index-llms-openai = "0.2.0"
```

**Comment by axiomofjoy** [comment]
Thanks @daringcalf. Can you downgrade `llama-index` to `0.11.1`?

**Comment by axiomofjoy** [comment]
Appears to be related to https://github.com/pydantic/pydantic/issues/7713

I am not able to reproduce with the provided script and using the following versions:

```
pydantic                                  2.8.2
pydantic-core                             2.20.1
llama-index                               0.11.2
llama-index-core                          0.11.2
openai                                    1.42.0
```

**Comment by daringcalf** [comment]
Thank you @axiomofjoy 

I wanted to clarify that I was initially using a different LLM provider than OpenAI, which I didn't mention in the code snippet because I thought it was irrelevant to the issue. However, after switching to OpenAI by using the following import:
```python
from llama_index.llms.openai import OpenAI
```
The `PydanticSerializationError` no longer occurred.

That said, I'm now encountering a different issue: the trace in `http://localhost:6006/projects/UHJvamVjdDox` is empty. While the code runs without errors, no data is being displayed in the Phoenix app.

Any guidance on why the trace might be empty or what additional steps I should take would be greatly appreciated.

**Comment by daringcalf** [comment]
After changing the line 

```python
LlamaIndexInstrumentor().instrument()
```
to
```python
endpoint = "http://127.0.0.1:6006/v1/traces"
tracer_provider = trace_sdk.TracerProvider()
tracer_provider.add_span_processor(SimpleSpanProcessor(OTLPSpanExporter(endpoint)))

LlamaIndexInstrumentor().instrument(tracer_provider=tracer_provider)
```
I'm now able to get the trace, and it works as expected.

However, I'm wondering if Phoenix only works with the LlamaIndex OpenAI integration or if it supports other LLMs as well. Any insights on this would be appreciated.

**Comment by axiomofjoy** [comment]
Thanks @daringcalf. Glad you got this working. What LLM were you using that was breaking? Do you mind sending the exact snippet to reproduce the issue?

> However, I'm wondering if Phoenix only works with the LlamaIndex OpenAI integration or if it supports other LLMs as well.

You should be able to use Phoenix with any of LlamaIndex's supported LLMs.

**Comment by daringcalf** [comment]
If I switch to another model, like this:
```python
Settings.llm = OpenRouter("openai/gpt-4o-mini")

Settings.llm = Neutrino(
    model="chat-preview",
    api_base="https://router.neutrinoapp.com/api/engines",
)
```
I still encounter the same old error:
```
Traceback (most recent call last):
  File "/Users/daringcalf/.local/share/virtualenvs/phoenix-F7TaqKv7/lib/python3.12/site-packages/openinference/instrumentation/llama_index/_handler.py", line 248, in process_output
    self[OUTPUT_VALUE] = result.model_dump_json(exclude_unset=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daringcalf/.local/share/virtualenvs/phoenix-F7TaqKv7/lib/python3.12/site-packages/pydantic/main.py", line 415, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

**Comment by daringcalf** [comment]
I found that by adding an additional parameter to the `instrument` call:
```python
LlamaIndexInstrumentor().instrument(
    tracer_provider=tracer_provider,
    use_legacy_callback_handler=True,
)
```
it works with other models as well.

I'm new to Phoenix, so I don't quite understand what the "legacy One-Click system" refers to. Could someone clarify what this option does and if there are any implications of using it?

**Comment by Jeremy-Hibiki** [comment]
I encoutered the same issue, and downgrade llama-index does not work (as long as it's 0.11.x)

Reproduction repo is here: https://github.com/Jeremy-Hibiki/phoenix-llama-index-pydantic-error

Use official OpenAI api is fine, but error with other OpenAI compatable servers like ollama or vLLM.

Output is below:

<details>

**With vLLM**

```bash
phoenix-llama-index-pydantic-error on  master is 󰏗 v0.1.0 via  v3.11.9 (phoenix-llama-index-pydantic-error) 󰍛 10GiB/23GiB 
 ❯ ./run.py --provider vllm
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
🔭 OpenTelemetry Tracing Details 🔭
|  Phoenix Project: phoenix-llama-index-pydantic-error
|  Span Processor: SimpleSpanProcessor
|  Collector Endpoint: https://app.phoenix.arize.com/v1/traces
|  Transport: HTTP
|  Transport Headers: {'api_key': '****'}
|  
|  Using a default SpanProcessor. `add_span_processor` will overwrite this default.
|  
|  `register` has set this TracerProvider as the global OpenTelemetry default.
|  To disable this behavior, call `register` with `set_global_tracer=False`.

API URL (http://localhost:8000/v1): 
API Key (EMPTY): 
Model (Qwen/Qwen2-0.5B-Instruct): 
INFO:httpx:HTTP Request: POST http://localhost:8000/v1/chat/completions "HTTP/1.1 200 OK"
ERROR:openinference.instrumentation.llama_index._handler:Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
Traceback (most recent call last):
  File "/data/projects/GitHub/phoenix-llama-index-pydantic-error/.venv/lib/python3.11/site-packages/openinference/instrumentation/llama_index/_handler.py", line 248, in process_output
    self[OUTPUT_VALUE] = result.model_dump_json(exclude_unset=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/GitHub/phoenix-llama-index-pydantic-error/.venv/lib/python3.11/site-packages/pydantic/main.py", line 415, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
ChatResponse(
    message=ChatMessage(role=<MessageRole.ASSISTANT: 'assistant'>, content='I am a large language model created by Alibaba Cloud. I am called Qwen.', additional_kwargs={'tool_calls': []}),
    raw=ChatCompletion(
        id='chat-b0550c65478e4eb095357d76d46e5ee0',
        choices=[
            Choice(
                finish_reason='stop',
                index=0,
                logprobs=None,
                message=ChatCompletionMessage(
                    content='I am a large language model created by Alibaba Cloud. I am called Qwen.',
                    refusal=None,
                    role='assistant',
                    function_call=None,
                    tool_calls=[]
                ),
                stop_reason=None
            )
        ],
        created=1725104997,
        model='Qwen/Qwen2-0.5B-Instruct',
        object='chat.completion',
        service_tier=None,
        system_fingerprint=None,
        usage=CompletionUsage(completion_tokens=18, prompt_tokens=23, total_tokens=41),
        prompt_logprobs=None
    ),
    delta=None,
    logprobs=None,
    additional_kwargs={'prompt_tokens': 23, 'completion_tokens': 18, 'total_tokens': 41}
)
```

**With OpenAI**

```bash
phoenix-llama-index-pydantic-error on  master is 󰏗 v0.1.0 via  v3.11.9 (phoenix-llama-index-pydantic-error) 󰍛 10GiB/23GiB took 3s 
 ❯ ./run.py --provider openai
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
🔭 OpenTelemetry Tracing Details 🔭
|  Phoenix Project: phoenix-llama-index-pydantic-error
|  Span Processor: SimpleSpanProcessor
|  Collector Endpoint: https://app.phoenix.arize.com/v1/traces
|  Transport: HTTP
|  Transport Headers: {'api_key': '****'}
|  
|  Using a default SpanProcessor. `add_span_processor` will overwrite this default.
|  
|  `register` has set this TracerProvider as the global OpenTelemetry default.
|  To disable this behavior, call `register` with `set_global_tracer=False`.

API URL (https://api.openai.com/v1): 
API Key (): 
Model (gpt-4o-mini): 
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
ChatResponse(
    message=ChatMessage(
        role=<MessageRole.ASSISTANT: 'assistant'>,
        content='I am an AI language model created by OpenAI, designed to assist with a wide range of questions and tasks by providing information, answering queries, and engaging in 
conversation. How can I help you today?',
        additional_kwargs={}
    ),
    raw=ChatCompletion(
        id='chatcmpl-A2GympfldZwiyayp3RD9Hc28AwdFT',
        choices=[
            Choice(
                finish_reason='stop',
                index=0,
                logprobs=None,
                message=ChatCompletionMessage(
                    content='I am an AI language model created by OpenAI, designed to assist with a wide range of questions and tasks by providing information, answering queries, and engaging in
conversation. How can I help you today?',
                    refusal=None,
                    role='assistant',
                    function_call=None,
                    tool_calls=None
                )
            )
        ],
        created=1725105288,
        model='gpt-4o-mini-2024-07-18',
        object='chat.completion',
        service_tier=None,
        system_fingerprint='fp_f33667828e',
        usage=CompletionUsage(completion_tokens=41, prompt_tokens=11, total_tokens=52)
    ),
    delta=None,
    logprobs=None,
    additional_kwargs={'prompt_tokens': 11, 'completion_tokens': 41, 'total_tokens': 52}
)
```

**With ollama**

```bash
phoenix-llama-index-pydantic-error on  master is 󰏗 v0.1.0 via  v3.11.9 (phoenix-llama-index-pydantic-error) 󰍛 10GiB/23GiB took 4s 
 ❯ ./run.py --provider ollama
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
🔭 OpenTelemetry Tracing Details 🔭
|  Phoenix Project: phoenix-llama-index-pydantic-error
|  Span Processor: SimpleSpanProcessor
|  Collector Endpoint: https://app.phoenix.arize.com/v1/traces
|  Transport: HTTP
|  Transport Headers: {'api_key': '****'}
|  
|  Using a default SpanProcessor. `add_span_processor` will overwrite this default.
|  
|  `register` has set this TracerProvider as the global OpenTelemetry default.
|  To disable this behavior, call `register` with `set_global_tracer=False`.

API URL (http://localhost:11434/v1): 
API Key (EMPTY): 
Model (qwen2:0.5b): 
INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
ERROR:openinference.instrumentation.llama_index._handler:Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
Traceback (most recent call last):
  File "/data/projects/GitHub/phoenix-llama-index-pydantic-error/.venv/lib/python3.11/site-packages/openinference/instrumentation/llama_index/_handler.py", line 248, in process_output
    self[OUTPUT_VALUE] = result.model_dump_json(exclude_unset=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/GitHub/phoenix-llama-index-pydantic-error/.venv/lib/python3.11/site-packages/pydantic/main.py", line 415, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
ChatResponse(
    message=ChatMessage(role=<MessageRole.ASSISTANT: 'assistant'>, content="I am a large language model created by Alibaba Cloud. I'm called Qwen.", additional_kwargs={}),
    raw=ChatCompletion(
        id='chatcmpl-861',
        choices=[
            Choice(
                finish_reason='stop',
                index=0,
                logprobs=None,
                message=ChatCompletionMessage(
                    content="I am a large language model created by Alibaba Cloud. I'm called Qwen.",
                    refusal=None,
                    role='assistant',
                    function_call=None,
                    tool_calls=None
                )
            )
        ],
        created=1725105472,
        model='qwen2:0.5b',
        object='chat.completion',
        service_tier=None,
        system_fingerprint='fp_ollama',
        usage=CompletionUsage(completion_tokens=18, prompt_tokens=12, total_tokens=30)
    ),
    delta=None,
    logprobs=None,
    additional_kwargs={'prompt_tokens': 12, 'completion_tokens': 18, 'total_tokens': 30}
)
```

</details>

**Comment by Jeremy-Hibiki** [comment]
After doing some bisecting with the OpenAI SDK version, i found openai==1.61.1 break the pydantic serialization.

https://github.com/openai/openai-python/releases/tag/v1.16.1

Meanwhile, there is an issue in the `openai-python` repo about this: https://github.com/openai/openai-python/issues/1306

A temporary workaround is to set an environment variable `DEFER_PYDANTIC_BUILD=0`, as https://github.com/openai/openai-python/issues/1306#issuecomment-2206955129 said. I've confirmed it works with the latest combination of `pydantic` and `openai-python`.

**Comment by Jeremy-Hibiki** [comment]
> I'm new to Phoenix, so I don't quite understand what the "legacy One-Click system" refers to. Could someone clarify what this option does and if there are any implications of using it?

llama-index has recently initiated a new mechanism more like OpenTelemetry to monitor your AI app called "instrumentation", since 0.10.20. 

Before that, we use "callbacks", which are deprecated and inconvenient for custom events. But if you use phoenix, they are almost the same thing because custom events are not recorded by phoenix, I guess?

More info is in the llama-index docs: https://docs.llamaindex.ai/en/stable/module_guides/observability/instrumentation

To be clear, I'm not a maintainer of either phoenix or llama-index.

**Comment by logan-markewich** [comment]
(heh doing the lords work @Jeremy-Hibiki 🙏🏻)

**Comment by enrico-stauss** [comment]
I ran into the same issue with the requirements given below. I'm not using any custom logic that involves callbacks and started looking into it. The issue seems to be coming from `llama-index-llms-groq` in my case, but the point I'm trying to make is, that the logging could be enhanced [here ](https://github.com/Arize-ai/openinference/blob/9e91a74700326281b5a45880b178f5d74e572995/python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py#L251) by printing out some information on the `instance` arg or alternatively a move verbose callstack. Now I unfortunately don't really know how the responsibilities are shared between `llama-index` and `openinference...llama_index` and the `instance` arg can be of `Any` type but maybe you have a better idea on how to resolve this. With you, I obviously don't refer to the maintainers of phoenix, as the issue lies elswhere.

I hope this helps in some way.

```
arize-phoenix                                 4.16.1
arize-phoenix-evals                           0.14.1
llama-cloud                                   0.0.15
llama-index                                   0.11.4
llama-index-agent-openai                      0.3.0
llama-index-callbacks-arize-phoenix           0.2.1
llama-index-cli                               0.3.0
llama-index-core                              0.11.4
llama-index-embeddings-databricks             0.2.0
llama-index-embeddings-openai                 0.2.4
llama-index-indices-managed-llama-cloud       0.3.0
llama-index-legacy                            0.9.48.post3
llama-index-llms-databricks                   0.2.0
llama-index-llms-groq                         0.2.0
llama-index-llms-openai                       0.2.2
llama-index-llms-openai-like                  0.2.0
llama-index-multi-modal-llms-openai           0.2.0
llama-index-postprocessor-cohere-rerank       0.2.0
llama-index-postprocessor-mixedbreadai-rerank 0.2.0
llama-index-program-openai                    0.2.0
llama-index-question-gen-openai               0.2.0
llama-index-readers-file                      0.2.0
llama-index-readers-llama-parse               0.3.0
llama-index-vector-stores-qdrant              0.3.0
llama-parse                                   0.5.1
openai                                        1.37.1
openinference-instrumentation                 0.1.9
openinference-instrumentation-langchain       0.1.23
openinference-instrumentation-llama-index     2.1.1
openinference-instrumentation-openai          0.1.9
openinference-semantic-conventions            0.1.9
opentelemetry-api                             1.26.0
opentelemetry-exporter-otlp                   1.26.0
opentelemetry-exporter-otlp-proto-common      1.26.0
opentelemetry-exporter-otlp-proto-grpc        1.26.0
opentelemetry-exporter-otlp-proto-http        1.26.0
opentelemetry-instrumentation                 0.47b0
opentelemetry-proto                           1.26.0
opentelemetry-sdk                             1.26.0
opentelemetry-semantic-conventions            0.47b0
pydantic                                      2.8.2
pydantic_core                                 2.20.1
```

**Comment by axiomofjoy** [comment]
This issue is resolved in `openinference-instrumentation-llama-index 3.0.1`

**Comment by stfines-clgx** [comment]
As of `openinference-instrumentation-llama-index 3.0.2` and `llama-index = "^0.12.1"` I receive this error with 
`Unable to serialize unknown type: <class 'llama_index.core.indices.vector_store.base.VectorStoreIndex'>`

**Comment by axiomofjoy** [comment]
> As of `openinference-instrumentation-llama-index 3.0.2` and `llama-index = "^0.12.1"` I receive this error with `Unable to serialize unknown type: <class 'llama_index.core.indices.vector_store.base.VectorStoreIndex'>`

Thanks @stfines-clgx, can you provide a code snippet to reproduce?
