### ISSUE TITLE
[BUG] Logout route fails

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4533]
ERROR:    Traceback (most recent call last):
  File "/Users/mikeldking/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/Users/mikeldking/anaconda3/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/mikeldking/work/phoenix/src/phoenix/server/app.py", line 412, in lifespan
    await stack.enter_async_context(grpc_server)
  File "/Users/mikeldking/anaconda3/lib/python3.10/contextlib.py", line 619, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/Users/mikeldking/work/phoenix/src/phoenix/server/grpc_server.py", line 86, in __aenter__
    server.add_insecure_port(f"[::]:{get_env_grpc_port()}")
  File "/Users/mikeldking/anaconda3/lib/python3.10/site-packages/grpc/aio/_server.py", line 94, in add_insecure_port
    return _common.validate_port_binding_result(
  File "/Users/mikeldking/anaconda3/lib/python3.10/site-packages/grpc/_common.py", line 181, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address [::]:4317; set GRPC_VERBOSITY=debug environment variable to see detailed error message.

**Comment by anticorrelator** [comment]
After looking into this a bit it seems unlikely that the issue is with binding to [::] since most systems should have ipv6 enabled by default barring some specific network settings. It's more likely that port 4317 was already in use for some reason and we failed to bind the GRPC port
