### ISSUE TITLE
[BUG]: RDS Postgres DB, local docker, Phoenix won't start

### ISSUE THREAD

**Issue by Mosquid** [Arize-ai/phoenix#5433]
**Describe the bug**
I had a docker compose with a local postgres that I've been using for my local dev environment. Once I changed the connection string to a remote DB (AWS RDS Postgres), my Phoenix container won't start.

**To Reproduce**
1. Create a docker-compose file

```
phoenix:
    image: arizephoenix/phoenix:latest 
    ports:
      - 6006:6006
      - 4317:4317
    environment:
       - PHOENIX_SQL_DATABASE_URL=<RDS postgres connection string>
```
2. run `docker compose up`
3. See error
```
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:6006 (Press CTRL+C to quit)
ERROR:    Traceback (most recent call last):
  File "/phoenix/env/phoenix/server/app.py", line 508, in lifespan
    yield {
  File "/phoenix/env/fastapi/routing.py", line 138, in merged_lifespan
    yield {**(maybe_nested_state or {}), **(maybe_original_state or {})}
  File "/phoenix/env/fastapi/routing.py", line 138, in merged_lifespan
    yield {**(maybe_nested_state or {}), **(maybe_original_state or {})}
  File "/phoenix/env/fastapi/routing.py", line 138, in merged_lifespan
    yield {**(maybe_nested_state or {}), **(maybe_original_state or {})}
  [Previous line repeated 1 more time]
  File "/phoenix/env/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/phoenix/env/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/phoenix/env/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/phoenix/env/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/phoenix/env/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/phoenix/env/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/phoenix/env/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/phoenix/env/phoenix/server/app.py", line 482, in lifespan
    async with AsyncExitStack() as stack:
  File "/usr/lib/python3.11/contextlib.py", line 733, in __aexit__
    raise exc_details[1]
  File "/usr/lib/python3.11/contextlib.py", line 716, in __aexit__
    cb_suppress = await cb(*exc_details)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/phoenix/env/phoenix/server/grpc_server.py", line 97, in __aexit__
    await self._server.stop(5)
  File "/phoenix/env/grpc/aio/_server.py", line 159, in stop
    await self._server.shutdown(grace)
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 1065, in shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 1069, in grpc._cython.cygrpc.AioServer.shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 1049, in _start_shutting_down
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 980, in _server_main_loop
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 959, in _request_call
asyncio.exceptions.CancelledError
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime [e.g. Jupyter, Colab]
 - Version latest

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)

**Comment by axiomofjoy** [comment]
Hey @Mosquid, have you verified that you are able to connect to your Postgres instance using the same connection string, for example, using `psql` or a similar tool?

**Comment by Mosquid** [comment]
Hey @axiomofjoy,

Thanks. Yes, I checked it with `pg_isready` and got `accepting connections`.

**Comment by axiomofjoy** [comment]
Hey @Mosquid, sorry you're hitting this issue. We're not clear what's going. Can you try disabling your gRPC server via the following flag and see if anything changes?

```
phoenix --read-only serve
```

**Comment by Mosquid** [comment]
I couldn't figure it out, so I ended up using persistent storage on my k8s cluster. But just FYI, it works when I run it in read-only mode. I hope this helps to identify the problem.

**Comment by RogerHYang** [comment]
@Mosquid Thank you so much for figuring this out. We have increased the parameter to 60 seconds in the latest release v7.3.1. Please give that a try and let us know if you encounter additional issues.
