### ISSUE TITLE
[BUG][playground] error message is uninformative for invalid invocation parameters

### ISSUE THREAD

**Issue by Parker-Stafford** [Arize-ai/phoenix#5441]
Edit: error messages are uninformative/ not actionable, e.g., for invalid invocation parameters

**Describe the bug**
When running the playground on a dataset if you hit an unhandled error the subscription onCompleted callback runs but not the onError (this is not the case with the mutation).

**To Reproduce**
1. Go to playground
2. select a dataset
3. switch to an anthropic model
4. don't set the max tokens (required, will throw)
5. click run and see subscription complete with no info

**Expected behavior**
onError would run (since unhandled) and user would be notified or error 

**Additional context**
onCompleted is running when the error is hit

error stack from server for one of the examples in the dataset, this same stack is logged for all examples in dataset

```
Required parameter max_tokens not provided
Traceback (most recent call last):
  File "/Users/parkerstafford/Library/Application Support/uv/tools/arize-phoenix/lib/python3.12/site-packages/phoenix/server/api/subscriptions.py", line 290, in chat_completion_over_dataset
    yield task.result()
          ^^^^^^^^^^^^^
  File "/Users/parkerstafford/Library/Application Support/uv/python/cpython-3.12.4-macos-aarch64-none/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/Users/parkerstafford/Library/Application Support/uv/tools/arize-phoenix/lib/python3.12/site-packages/phoenix/server/api/subscriptions.py", line 435, in _as_coroutine
    return await iterable.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parkerstafford/Library/Application Support/uv/tools/arize-phoenix/lib/python3.12/site-packages/phoenix/server/api/subscriptions.py", line 326, in _stream_chat_completion_over_dataset_example
    invocation_parameters = llm_client.construct_invocation_parameters(input.invocation_parameters)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parkerstafford/Library/Application Support/uv/tools/arize-phoenix/lib/python3.12/site-packages/phoenix/server/api/helpers/playground_clients.py", line 209, in construct_invocation_parameters
    validate_invocation_parameters(supported_params, formatted_invocation_parameters)
  File "/Users/parkerstafford/Library/Application Support/uv/tools/arize-phoenix/lib/python3.12/site-packages/phoenix/server/api/input_types/InvocationParameters.py", line 147, in validate_invocation_parameters
    raise ValueError(f"Required parameter {param_def.invocation_name} not provided")
```

**Comment by axiomofjoy** [comment]
Raising an error from subscription would stop the entire experiment run, e.g., if one error occurs one a single dataset example.

**Comment by axiomofjoy** [comment]
In addition to the stacktrace, the way this error manifests is we get an uninformative error message for each dataset example. Pretty confusing for the user.

<img width="1097" alt="Screenshot 2024-12-10 at 3 49 43 PM" src="https://github.com/user-attachments/assets/04288fd7-a162-461a-b202-a57572a40696">
