### ISSUE TITLE
[BUG] feature discovery doesn't account for `prediction_id` being currently a reserved field

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#632]
**Describe the bug**
```
Traceback (most recent call last):
  File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/mikeldking/work/phoenix/src/phoenix/server/main.py", line 88, in <module>
    model = create_model_from_datasets(
  File "/Users/mikeldking/work/phoenix/src/phoenix/core/model_schema_adapter.py", line 92, in create_model_from_datasets
    return Schema(
  File "<string>", line 14, in __init__
  File "/Users/mikeldking/work/phoenix/src/phoenix/core/model_schema.py", line 912, in __post_init__
    raise ValueError(
ValueError: `prediction_id` is specified as both `PREDICTION_ID` and `FEATURE`

```

**To Reproduce**
1. ingest records that already have a `prediction_id` column
2. See above

**Expected behavior**
No error

**Environment (please complete the following information):**
 - Version [e.g. 0.0.15

**Additional context**
The idea of having reserved names largely feels problematic in this regard. I would consider trying to not use this concept.

**Comment by mikeldking** [comment]
@RogerHYang notes that this could be root-caused in multiple schemas. We should consider consolidating.

**Comment by RogerHYang** [comment]
@mikeldking actually, your original assessment is accurate: both of these are in the same schema, it's a matter of reserved names colliding with an existing one
