### ISSUE TITLE
[BUG] cannot find index.html

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#802]
**Describe the bug**
Phoenix does not launch, I see "Internal Server Error" when I open a browser tab.

<img width="334" alt="Screenshot 2023-05-30 at 5 23 29 PM" src="https://github.com/Arize-ai/phoenix/assets/15664869/a117bbcc-d946-4223-b990-eecd8feb5249">

I see the following in the notebook cell output.

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/Users/xandersong/phoenix/src/phoenix/server/app.py", line 55, in dispatch
    response = await call_next(request)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/staticfiles.py", line 103, in __call__
    response = await self.get_response(path, scope)
  File "/Users/xandersong/phoenix/src/phoenix/server/app.py", line 42, in get_response
    raise RuntimeError("Failed to find index.html")
RuntimeError: Failed to find index.html
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/Users/xandersong/phoenix/src/phoenix/server/app.py", line 55, in dispatch
    response = await call_next(request)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/Users/xandersong/.virtualenvs/phoenixdev/lib/python3.8/site-packages/starlette/staticfiles.py", line 103, in __call__
    response = await self.get_response(path, scope)
  File "/Users/xandersong/phoenix/src/phoenix/server/app.py", line 42, in get_response
    raise RuntimeError("Failed to find index.html")
RuntimeError: Failed to find index.html
```

**To Reproduce**
Run this notebook with the attached data (you need to change the path to the file in the notebook).

[anyscale_experiments.zip](https://github.com/Arize-ai/phoenix/files/11607362/anyscale_experiments.zip)

**Expected behavior**
I expect Phoenix to launch without issue

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Jupyter
 - Browser: Chrome
 - Version: commit 007210b on `anyscale-finetuning-workshop` branch (basically latest main)

**Comment by mikeldking** [comment]
Cannot reproduce
