### ISSUE TITLE
[BUG] hashing numpy arrays error

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#852]
**Describe the bug**
When I switched the context retrieval notebook to use `prompt_column_names` and `response_column_names` instead of `embedding_feature_column_names`, Phoenix successfully launches, but an error appears in the notebook:

```
unhashable type: 'numpy.ndarray'
Traceback (most recent call last):
  File "/Users/xandersong/phoenix/src/phoenix/metrics/__init__.py", line 71, in __call__
    return self.calc(df)
  File "/Users/xandersong/phoenix/src/phoenix/metrics/mixins.py", line 212, in calc
    merged_counts = pd.merge(
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 162, in merge
    return op.get_result(copy=copy)
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 809, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1051, in _get_join_info
    join_index, left_indexer, right_indexer = left_ax.join(
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 259, in join
    join_index, lidx, ridx = meth(self, other, how=how, level=level, sort=sort)
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 4498, in join
    if not self.is_unique and not other.is_unique:
  File "pandas/_libs/properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 2238, in is_unique
    return self._engine.is_unique
  File "pandas/_libs/index.pyx", line 236, in pandas._libs.index.IndexEngine.is_unique.__get__
  File "pandas/_libs/index.pyx", line 241, in pandas._libs.index.IndexEngine._do_unique_check
  File "pandas/_libs/index.pyx", line 303, in pandas._libs.index.IndexEngine._ensure_mapping_populated
  File "pandas/_libs/hashtable_class_helper.pxi", line 7114, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'numpy.ndarray'
unhashable type: 'numpy.ndarray'
Traceback (most recent call last):
  File "/Users/xandersong/phoenix/src/phoenix/metrics/__init__.py", line 71, in __call__
    return self.calc(df)
  File "/Users/xandersong/phoenix/src/phoenix/metrics/metrics.py", line 101, in calc
    return cast(float, data.nunique())
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/base.py", line 1068, in nunique
    uniqs = self.unique()
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/series.py", line 2194, in unique
    return super().unique()
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/base.py", line 1030, in unique
    result = algorithms.unique1d(values)
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/algorithms.py", line 390, in unique
    return unique_with_mask(values)
  File "/Users/xandersong/miniforge3/envs/llama-index/lib/python3.10/site-packages/pandas/core/algorithms.py", line 429, in unique_with_mask
    uniques = table.unique(values)
  File "pandas/_libs/hashtable_class_helper.pxi", line 7247, in pandas._libs.hashtable.PyObjectHashTable.unique
  File "pandas/_libs/hashtable_class_helper.pxi", line 7194, in pandas._libs.hashtable.PyObjectHashTable._unique
TypeError: unhashable type: 'numpy.ndarray'
```

**To Reproduce**
Run [this version of the context retrieval notebook](https://colab.research.google.com/drive/1h9eSNo5LBjeoJtrUv1Pgbz4x_pcjAPJ0?usp=sharing) and launch Phoenix. You don't need to run the LLM-assisted evaluation code, you can just run with the downloaded data.

**Expected behavior**
I expect Phoenix to launch and run without error.

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Jupyter
 - Browser: Chrome
 - Version: commit `ab3afc7` on `llama-index-docs` (no source code changes relative to `main`)

**Comment by RogerHYang** [comment]
This comes from PSI being now calculated on `text_vector` because it's now treated as a feature variable with each vector being a discrete category. And the printout is now showing because we recently added `logger.warning` in https://github.com/Arize-ai/phoenix/pull/838.
