### ISSUE TITLE
[ENHANCEMENT] support multi-label data

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#885]
**Is your feature request related to a problem? Please describe.**
Support multi-label output in the `actual_label_column_name` field. The 

**Describe the solution you'd like**
- Support sparse multi-label use-cases. Entries of the `actual_label_column_name` field would be lists of strings, indicating the classes to which each example belongs
- Document support for multi-label use cases (in FAQ)

**Describe alternatives you've considered**
- entries of the `actual_label_column_name` field can be dense boolean numpy arrays, indicating whether each entry belongs to the ith class
- requires a map from indexes to class names, seems clunky

**Additional context**
Hi everyone!
Been having a great time getting started with Phoenix so far but just hit a wall.
How do I best treat sparse multilabel data?
I have text snippets that contain many labels each, so I tried adding this as a list of strings to the actual_label_column_name column but get a:
We strive to do our very best but 🐛 bugs happen. It would mean a lot to us if you could file a an issue. If you feel comfortable, please include the error details below in your issue. We will get back to you as soon as we can.
when i open it in the visualizer GUI.
Guessing its a missing feature but wanted to check in on advice for what to do in the meantime?

**Comment by ArthurBook** [comment]
Thanks a lot for opening up this ticket. This feature would be awesome to have!

**Comment by axiomofjoy** [comment]
Needs to support high cardinality
```
the cardinality is pretty huge. probably north of 200k classes
```

**Comment by axiomofjoy** [comment]
A little more color on this ticket from @ArthurBook. Use-case is named entity recognition, they have a model that is predicting the presence/ absence of >200K named entities in pieces of text. They are using embeddings for the text to visualize in UMAP. Dataset they are working on is ~30K rows. So a very wide and not super deep dataset.

**Comment by axiomofjoy** [comment]
This might be a use-case where we consider supporting sparse columns in pandas.

**Comment by axiomofjoy** [comment]
![Selection_055](https://github.com/Arize-ai/phoenix/assets/15664869/c93ccbbe-93a9-4e35-a947-f3ca100e3a2a)

```
GraphQL request:9:7
 8 |     ... on Dimension {
 9 |       segmentsComparison(primaryTimeRange: $timeRange) {
   |       ^
10 |         segments {
Traceback (most recent call last):
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/graphql/execution/execute.py", line 521, in execute_field
    result = resolve_fn(source, info, **args)
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 597, in _resolver
    return _get_result_with_extensions(
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 583, in extension_resolver
    return reduce(
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 578, in wrapped_get_result
    return _get_result(
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 539, in _get_result
    return field.get_result(
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/strawberry/field.py", line 177, in get_result
    return self.base_resolver(*args, **kwargs)
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/strawberry/types/fields/resolver.py", line 187, in __call__
    return self.wrapped_func(*args, **kwargs)
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/phoenix/server/api/types/Dimension.py", line 229, in segments_comparison
    summaries[role] = binning_method.segmented_summary(
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/phoenix/metrics/binning.py", line 283, in segmented_summary
    return dataframe.groupby(
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1353, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1402, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 755, in apply
    splitter = self._get_splitter(data, axis=axis)
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 736, in _get_splitter
    ids, _, ngroups = self.group_info
  File "pandas/_libs/properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 873, in group_info
    comp_ids, obs_group_ids = self._get_compressed_codes()
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 897, in _get_compressed_codes
    return ping.codes, np.arange(len(ping.group_index), dtype=np.intp)
  File "pandas/_libs/properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 720, in group_index
    return Index._with_infer(uniques, name=self.name)
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 671, in _with_infer
    result = cls(*args, **kwargs)
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 562, in __new__
    arr = klass._ensure_array(arr, arr.dtype, copy=False)
  File "/home/recoverx/.cache/pypoetry/virtualenvs/drift-buster-cwE93gL1-py3.8/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 575, in _ensure_array
    raise NotImplementedError("float16 indexes are not supported")
NotImplementedError: float16 indexes are not supported
```

**Comment by axiomofjoy** [comment]
Need to also check if color by > dimension > tag > tag name works for a wide dataset like this.
