### ISSUE TITLE
[BUG] "Failed to load the point events" error message

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#888]
**Describe the bug**

"Failed to load the point events" error message appears when using Phoenix. Stacktrace below.

```
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
'1'

GraphQL request:23:7
22 |     referenceDataset {
23 |       events(eventIds: $referenceEventIds) {
   |       ^
24 |         id
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/graphql/execution/execute.py", line 521, in execute_field
    result = resolve_fn(source, info, **args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/schema/schema_converter.py", line 597, in _resolver
    return _get_result_with_extensions(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/schema/schema_converter.py", line 583, in extension_resolver
    return reduce(
           ^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/schema/schema_converter.py", line 578, in wrapped_get_result
    return _get_result(
           ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/schema/schema_converter.py", line 539, in _get_result
    return field.get_result(
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/field.py", line 177, in get_result
    return self.base_resolver(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/types/fields/resolver.py", line 187, in __call__
    return self.wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/phoenix/server/api/types/Dataset.py", line 42, in events
    row_ids = parse_event_ids(event_ids)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/phoenix/server/api/types/Event.py", line 53, in parse_event_ids
    row_id, dataset_role = unpack_event_id(event_id)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/phoenix/server/api/types/Event.py", line 43, in unpack_event_id
    dataset_role = ms.DatasetRole[dataset_role_str.split(".")[-1]]
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/enum.py", line 789, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: '1'
Stack (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/asgi/__init__.py", line 111, in __call__
    return await self.handle_http(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/asgi/__init__.py", line 178, in handle_http
    response = await self.run(request)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/http/async_base_view.py", line 176, in run
    result = await self.execute_operation(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/http/async_base_view.py", line 115, in execute_operation
    return await self.schema.execute(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/schema/schema.py", line 248, in execute
    result = await execute(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/langchain_dev/lib/python3.11/site-packages/strawberry/schema/execute.py", line 156, in execute
    process_errors(result.errors, execution_context)
```

**To Reproduce**

Run [LangChain/ Pinecone workshop notebook](https://colab.research.google.com/github/Arize-ai/phoenix/blob/langchain-pinecone-search-and-retrieval/tutorials/langchain_pinecone_search_and_retrieval.ipynb).

**Screenshots**

![Screenshot 2023-06-24 at 3 33 55 PM](https://github.com/Arize-ai/phoenix/assets/15664869/1a2d467b-82c1-41d2-ad2f-d9488437d916)

**Environment (please complete the following information):**
 - OS: Mac OS Ventura 13.4
 - Notebook Runtime: Jupyter
 - Browser: Chrome
 - Version: 0.0.24

**Comment by axiomofjoy** [comment]
Reply to Jonathan Hodges in Slack community once ticket is investigated.

**Comment by RogerHYang** [comment]
There appears to be a breaking change in python 3.11 for turning `IntEnum` into strings, and that's causing our lookups to fail. See screenshot below.

## python 3.10
<img width="705" alt="Screenshot 2023-06-26 at 11 47 47 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/1026cab6-4970-4209-b955-b03963bbd165">


## python 3.11
<img width="719" alt="Screenshot 2023-06-26 at 11 38 35 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/4f94b36f-8af7-4325-9e75-ef010eb1d862">

**Comment by RogerHYang** [comment]
> Changed in version 3.11: [__str__()](https://docs.python.org/3/reference/datamodel.html#object.__str__) is now int.__str__() to better support the replacement of existing constants use-case. [__format__()](https://docs.python.org/3/reference/datamodel.html#object.__format__) was already int.__format__() for that same reason.

[python doc](https://docs.python.org/3/library/enum.html#enum.IntEnum:~:text=with%201.-,Changed%20in%20version%203.11%3A%20__str__()%20is%20now%20int.__str__()%20to%20better%20support%20the%20replacement%20of%20existing%20constants%20use%2Dcase.%20__format__()%20was%20already%20int.__format__()%20for%20that%20same%20reason.,-class%20enum.)
